language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
addons:
  firefox: latest-esr
before_install:
  # install geckdriver for firefox
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzvf geckodriver-v0.22.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - pip install tox-travis
script: tox
after_success:
- coveralls
deploy:
  provider: pypi
  skip_existing: true
  user: mshriver
  password:
    secure: W3VU0iJpn6W/H0encF5gA7UXtP82YoJq/qha0ECb3/vHzOZVs6qV0UGevWkoZZVOpidstYkH3CFWn8EO6BoY6OJGXMqTqHVKkkoXA3F16MGcHrnD/PG1ePYoIomwkiE/QLtZgjMEIYpgH2RHrf3GaNpPGN53u8wNMDLtn4AFfjIastCL1e9gPQhCd5Gxdtrjiba/Ht+S15ZJduL9LXxULlBcL+p9a309KQtq7d9noW7ZDfMxmVHoajKpa+OblMme4NqlOLGqglPKTPcKC4wKpMyLeeRYaB6fzSTCpPXrQ6sILCiFtIUyvziOm5Q91Qdq3thlA7bcXPT0PE2mc7grzAZJEyCCLJyMZk14B7Z04CKwFmm/UZ2SVBhjw+vmGgjhkpNh0a1kcdA0WAepVlVP/k95cGdYoRFFSBPWMulPZ/5mThpyeSTCI+Oq7BCCmrhi4ojY8qKk2l5w2wrn3XqFBYipHzcIT3IB+Xp31d8sQXbeKzW6a2CUS6AwD8nVqjB3V9hC3stRPOFKqf23U+GkAu2jd424OuUIoa/TYzYP44CplvfIRffJiwUJQYnUEXwpZDLnvShIlYCD4Hqha/DL3D/PFGVuGdTvgvw6mnqqPYgl27QzyYKQYRvTc8+lYAQs0sq1UWmc0OBZb4PA0vrQFLoOhK3KtTuAKhikH2mILiw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: RedHatQE/widgetastic.patternfly
